### PR TITLE
Updating for Deno 0.41.0 🦕 

### PR DESCRIPTION
**Pull request by olaven**
Needed this for my own project and thought I'd post a PR 😄

### CODE REVIEW

**Comment by olaven** [comment]
`deno test -A` passes on my machine. However, the same command break in the CI. 
It seems like the /std/fs is not use the updated `FileInfo`.. Not sure though, seems like there is something I am not understanding. 😕 

I get similar errors when actually running, i.e. `denon program.ts`

**Comment by eliassjogreen** [comment]
The errors you get when running could be because of you not reinstalling the denon cli when testing. Try `deno install denon --allow-read --allow-run -f .\denon.ts` when locally testing.

**Comment by eliassjogreen** [comment]
The tests failing could be because you didn't update the `test_deps.ts` dependencies

**Comment by olaven** [comment]
@eliassjogreen You're right, thanks! I have updated both in the latest commit.

**Pull request merged**
